import bcrypt from 'bcryptjs';

export const initialCategories = [
  {
    name: 'Heritage',
    slug: 'heritage',
    description: 'UNESCO World Heritage monuments, royal palaces, and ancient civilizational landmarks.',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80',
    isActive: true,
  },
  {
    name: 'Forts',
    slug: 'forts',
    description: 'Impregnable citadels, hill bastions, and royal defense structures echoing India’s martial valor.',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
    isActive: true,
  },
  {
    name: 'Temples',
    slug: 'temples',
    description: 'Sacred architectural marvels, Dravidian gopurams, Nagara spires, and spiritual shrines.',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
    isActive: true,
  },
  {
    name: 'Nature',
    slug: 'nature',
    description: 'Lush valleys, serene backwaters, mist-laden plantations, and pristine natural landscapes.',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
    isActive: true,
  },
  {
    name: 'Religious',
    slug: 'religious',
    description: 'Holy pilgrimage towns, sacred rivers, ancient ghats, and spiritual epicenters.',
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80',
    isActive: true,
  },
  {
    name: 'Hill Stations',
    slug: 'hill-stations',
    description: 'High-altitude mountain retreats, colonial summer capitals, and snow-crowned valleys.',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80',
    isActive: true,
  },
  {
    name: 'Beaches',
    slug: 'beaches',
    description: 'Sun-kissed sands, Arabian Sea sunsets, tropical palm groves, and coastal shores.',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
    isActive: true,
  },
  {
    name: 'Wildlife',
    slug: 'wildlife',
    description: 'National parks, tiger reserves, rhinoceros habitats, and biodiverse sanctuaries.',
    image: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=1200&q=80',
    isActive: true,
  },
  {
    name: 'Historical',
    slug: 'historical',
    description: 'Archaeological wonders, ancient ruins, rock-cut caves, and chronologies of dynasties.',
    image: 'https://images.unsplash.com/photo-1600100397608-f010f443b593?auto=format&fit=crop&w=1200&q=80',
    isActive: true,
  },
  {
    name: 'Cultural',
    slug: 'cultural',
    description: 'Living traditions, classical arts, artisanal bazaars, and rich regional folklore.',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=80',
    isActive: true,
  },
  {
    name: 'Architecture',
    slug: 'architecture',
    description: 'Indo-Saracenic, Mughal, Rajput, and ancient Dravidian engineering feats.',
    image: 'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=1200&q=80',
    isActive: true,
  },
  {
    name: 'Lakes',
    slug: 'lakes',
    description: 'High-altitude crystal waters, urban royal lakes, and serene freshwater ecosystems.',
    image: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=1200&q=80',
    isActive: true,
  },
  {
    name: 'Adventure',
    slug: 'adventure',
    description: 'White-water river rafting, Himalayan trekking, desert safaris, and high-altitude camping.',
    image: 'https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?auto=format&fit=crop&w=1200&q=80',
    isActive: true,
  },
  {
    name: 'Museums',
    slug: 'museums',
    description: 'Curated archives, royal armories, numismatic treasures, and rare antiquities.',
    image: 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=1200&q=80',
    isActive: true,
  },
  {
    name: 'Waterfalls',
    slug: 'waterfalls',
    description: 'Cascading torrential falls, monsoon cataracts, and deep Western Ghat gorges.',
    image: 'https://images.unsplash.com/photo-1546587348-d12660c30c50?auto=format&fit=crop&w=1200&q=80',
    isActive: true,
  },
];

export const initialStates = [
  {
    name: 'Uttar Pradesh',
    slug: 'uttar-pradesh',
    type: 'State',
    capital: 'Lucknow',
    description: 'The heartland of Indian heritage, cradle of sacred rivers Ganga and Yamuna, home to the iconic Taj Mahal, holy Kashi, and exquisite Awadhi craftsmanship.',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80',
    culture: 'Rich confluence of Ganga-Jamuni Tehzeeb, classical Kathak dance, and centuries-old zardozi embroidery.',
    cuisine: 'Awadhi Biryani, Galouti Kebab, Bedmi Puri, Petha of Agra, and Malaiyo of Varanasi.',
    festivals: ['Kumbh Mela', 'Dev Deepawali', 'Taj Mahotsav', 'Holi of Barsana', 'Janmashtami'],
    geography: 'Spanning the vast fertile Indo-Gangetic plains with Himalayan foothills along the northern border.',
    isActive: true,
  },
  {
    name: 'Rajasthan',
    slug: 'rajasthan',
    type: 'State',
    capital: 'Jaipur',
    description: 'The Land of Kings, world-renowned for majestic desert citadels, gilded palaces, vibrant folk music, and legendary Rajput chivalry.',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
    culture: 'Kalbelia and Ghoomar folk dances, royal polo traditions, puppet theater, and bandhani textiles.',
    cuisine: 'Dal Baati Churma, Ker Sangri, Laal Maas, Ghevar, and Pyaaz Kachori.',
    festivals: ['Pushkar Camel Fair', 'Desert Festival Jaisalmer', 'Teej', 'Gangaur', 'Jaipur Literature Festival'],
    geography: 'Dominated by the ancient Aravalli mountain range and the vast Thar Desert.',
    isActive: true,
  },
  {
    name: 'Maharashtra',
    slug: 'maharashtra',
    type: 'State',
    capital: 'Mumbai',
    description: 'India’s economic powerhouse blending Arabian Sea coastlines, Maratha hill forts, ancient rock-cut UNESCO caves, and bustling cosmopolitan energy.',
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80',
    culture: 'Lavani folk dance, Ganeshotsav celebrations, Warli tribal art, and deep Maratha warrior history.',
    cuisine: 'Misal Pav, Puran Poli, Vada Pav, Pithla Bhakri, and coastal Malvani fish curry.',
    festivals: ['Ganesh Chaturthi', 'Gudi Padwa', 'Shivaji Maharaj Jayanti', 'Ellora Ajanta Festival'],
    geography: 'Comprises the Konkan coast, Western Ghats (Sahyadris), and the expansive Deccan Plateau.',
    isActive: true,
  },
  {
    name: 'Kerala',
    slug: 'kerala',
    type: 'State',
    capital: 'Thiruvananthapuram',
    description: 'Known as "God’s Own Country", blessed with serene backwaters, emerald tea estates, Ayurvedic wellness retreats, and coastal spice ports.',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
    culture: 'Kathakali classical dance drama, Kalaripayattu martial arts, and ornate snake boat regattas.',
    cuisine: 'Appam with Stew, Kerala Sadya on banana leaf, Karimeen Pollichathu, and Malabar Biryani.',
    festivals: ['Onam', 'Vishu', 'Thrissur Pooram', 'Nehru Trophy Boat Race'],
    geography: 'Narrow coastal strip wedged between the Arabian Sea and the biodiversity-rich Western Ghats.',
    isActive: true,
  },
  {
    name: 'Karnataka',
    slug: 'karnataka',
    type: 'State',
    capital: 'Bengaluru',
    description: 'A land of royal heritage and modern innovation, featuring the boulder-strewn Vijayanagara ruins of Hampi, Mysore palaces, and aromatic coffee hills.',
    image: 'https://images.unsplash.com/photo-1600100397608-f010f443b593?auto=format&fit=crop&w=1200&q=80',
    culture: 'Yakshagana folk theater, Carnatic musical traditions, Mysore silk, and sandalwood carvings.',
    cuisine: 'Bisi Bele Bath, Mysore Pak, Neer Dosa, Mangalorean Ghee Roast, and Coorg Pandi Curry.',
    festivals: ['Mysuru Dasara', 'Hampi Utsav', 'Kambala Buffalo Race', 'Karaga'],
    geography: 'Western coastal Karavali, Sahyadri highlands, and the undulating Deccan plateau.',
    isActive: true,
  },
  {
    name: 'Tamil Nadu',
    slug: 'tamil-nadu',
    type: 'State',
    capital: 'Chennai',
    description: 'A bastion of Dravidian civilization famous for towering temple gopurams, classical Bharatanatyam, timeless bronze sculpture, and ancient coastal towns.',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
    culture: 'Bharatanatyam dance, Carnatic Margazhi festival, Tanjore painting, and Kanchipuram silk weaving.',
    cuisine: 'Chettinad Pepper Chicken, Masala Dosa, Filter Coffee, Pongal, and Idli with Sambhar.',
    festivals: ['Pongal', 'Natyanjali Dance Festival', 'Chithirai Festival Madurai', 'Jallikattu'],
    geography: 'Coromandel coastal plains, Eastern Ghats, Nilgiri hills, and southernmost tip at Kanyakumari.',
    isActive: true,
  },
  {
    name: 'West Bengal',
    slug: 'west-bengal',
    type: 'State',
    capital: 'Kolkata',
    description: 'The cultural capital of India, cradle of the Bengal Renaissance, Himalayan hill retreat Darjeeling, and the wild mangrove forests of Sundarbans.',
    image: 'https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=1200&q=80',
    culture: 'Rabindra Sangeet, Baul folk singing, Pattachitra scroll painting, and grand Durga Puja carnivals.',
    cuisine: 'Macher Jhol, Kosha Mangsho, Rasgulla, Sandesh, Mishti Doi, and Kolkata Kathi Rolls.',
    festivals: ['Durga Puja', 'Poila Boishakh', 'Kolkata Book Fair', 'Poush Mela Shantiniketan'],
    geography: 'Extends from snow-capped Kanchenjunga peaks in the north to the Bay of Bengal delta in the south.',
    isActive: true,
  },
  {
    name: 'Odisha',
    slug: 'odisha',
    type: 'State',
    capital: 'Bhubaneswar',
    description: 'Ancient Kalinga, known for the stone chariot of Konark Sun Temple, sacred seaside Puri Jagannath, Chilika lagoon, and silver filigree art.',
    image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
    culture: 'Odissi classical dance, Gotipua acrobatics, Pattachitra paintings, and Sambalpuri handlooms.',
    cuisine: 'Chhena Poda, Dalma, Machha Besara, Rasabali, and Khaja.',
    festivals: ['Ratha Yatra Puri', 'Konark Dance Festival', 'Bali Jatra', 'Raja Parba'],
    geography: 'Long coastline along the Bay of Bengal, Eastern Ghat hills, and fertile deltaic river systems.',
    isActive: true,
  },
  {
    name: 'Assam',
    slug: 'assam',
    type: 'State',
    capital: 'Dispur',
    description: 'The gateway to Northeast India, famous for the mighty Brahmaputra river, emerald tea plantations, Muga golden silk, and one-horned rhinos.',
    image: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=1200&q=80',
    culture: 'Bihu folk dance, Sattriya classical tradition, bamboo and cane craft, and Muga silk weaving.',
    cuisine: 'Khaar, Masor Tenga (sour fish curry), Duck with Ash Gourd, and Pitha rice cakes.',
    festivals: ['Rongali Bihu', 'Bhogali Bihu', 'Ambubachi Mela', 'Majuli Raas Mahotsav'],
    geography: 'Brahmaputra and Barak river valleys surrounded by lush sub-Himalayan hills.',
    isActive: true,
  },
  {
    name: 'Goa',
    slug: 'goa',
    type: 'State',
    capital: 'Panaji',
    description: 'A sun-drenched coastal haven renowned for golden sand beaches, Portuguese colonial architecture, spice plantations, and relaxed "Susegad" living.',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
    culture: 'Unique Indo-Portuguese synthesis, brass bands, Konkani folk singing, and ornate Catholic churches.',
    cuisine: 'Goan Fish Curry, Pork Vindaloo, Bebinca, Xacuti, and cashew Feni.',
    festivals: ['Goa Carnival', 'Shigmo', 'Feast of St. Francis Xavier', 'Sunburn Music Festival'],
    geography: 'Coastal strip along the Konkan, laced with rivers Mandovi and Zuari descending from the Western Ghats.',
    isActive: true,
  },
  {
    name: 'Punjab',
    slug: 'punjab',
    type: 'State',
    capital: 'Chandigarh',
    description: 'The land of five rivers, celebrated for the golden brilliance of Sri Harmandir Sahib, warm hospitable spirit, fertile agricultural fields, and energetic Bhangra.',
    image: 'https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&w=1200&q=80',
    culture: 'Bhangra and Giddha folk dances, Phulkari embroidery, and hearty communal Langar traditions.',
    cuisine: 'Sarson da Saag & Makki di Roti, Butter Chicken, Amritsari Kulcha, and rich creamy Lassi.',
    festivals: ['Baisakhi', 'Lohri', 'Hola Mohalla', 'Gurpurab'],
    geography: 'Vast fertile alluvial plain fed by the Sutlej, Beas, and Ravi rivers.',
    isActive: true,
  },
  {
    name: 'Madhya Pradesh',
    slug: 'madhya-pradesh',
    type: 'State',
    capital: 'Bhopal',
    description: 'The "Heart of India", boasting the erotic temple carvings of Khajuraho, Emperor Ashoka’s Sanchi Stupa, tiger reserves, and ancient hill forts.',
    image: 'https://images.unsplash.com/photo-1620619767323-b95a89183081?auto=format&fit=crop&w=1200&q=80',
    culture: 'Gond and Bhil tribal art, Khajuraho dance festival, and Malwa folk traditions.',
    cuisine: 'Poha Jalebi, Dal Bafla, Bhutte Ka Kees, and Mawa Bati.',
    festivals: ['Khajuraho Dance Festival', 'Tansen Music Festival', 'Bhagoria Haat', 'Lokrang'],
    geography: 'Central plateau with Vindhya and Satpura mountain ranges, dense sal forests, and Narmada river valley.',
    isActive: true,
  },
  {
    name: 'Delhi',
    slug: 'delhi',
    type: 'Union Territory',
    capital: 'New Delhi',
    description: 'India’s historic national capital territory, where centuries of sultanates, Mughal emperors, and modern republic intersect through monumental architecture.',
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1200&q=80',
    culture: 'Cosmopolitan convergence of pan-Indian arts, street food havens, classical concerts, and heritage walks.',
    cuisine: 'Chole Bhature, Butter Chicken, Dahi Bhalla, Chandni Chowk Paranthas, and Nihari.',
    festivals: ['Independence Day at Red Fort', 'Republic Day Parade', 'Qutub Festival', 'Dussehra'],
    geography: 'Yamuna floodplain bordered by the northern extension of the Aravalli Ridge.',
    isActive: true,
  },
  {
    name: 'Jammu and Kashmir',
    slug: 'jammu-and-kashmir',
    type: 'Union Territory',
    capital: 'Srinagar (Summer) / Jammu (Winter)',
    description: 'Crown of Bharat, celebrated for snow-draped Himalayan crests, tranquil Dal Lake houseboats, Mughal gardens, and alpine meadows.',
    image: 'https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=1200&q=80',
    culture: 'Pashmina shawl craftsmanship, papier-mâché art, Sufi musical heritage, and wood carving.',
    cuisine: 'Wazwan feast, Rogan Josh, Kahwa saffron tea, Gushtaba, and Dum Aloo.',
    festivals: ['Tulip Festival', 'Shikara Festival', 'Baisakhi', 'Hemis Festival'],
    geography: 'Magnificent Himalayan and Pir Panjal ranges enclosing the fertile Kashmir Valley and Chenab river basin.',
    isActive: true,
  },
];

export const initialCities = [
  { name: 'Agra', slug: 'agra', stateSlug: 'uttar-pradesh', stateName: 'Uttar Pradesh', description: 'City of the Taj Mahal and Mughal imperial grandeur on the banks of Yamuna.', image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Varanasi', slug: 'varanasi', stateSlug: 'uttar-pradesh', stateName: 'Uttar Pradesh', description: 'One of the world’s oldest living cities, spiritual center on sacred Ganga.', image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Jaipur', slug: 'jaipur', stateSlug: 'rajasthan', stateName: 'Rajasthan', description: 'The Pink City, royal capital of Rajasthan filled with palaces and vibrant bazars.', image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Udaipur', slug: 'udaipur', stateSlug: 'rajasthan', stateName: 'Rajasthan', description: 'The City of Lakes, romantic gem with marble palaces shimmering on Lake Pichola.', image: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Jodhpur', slug: 'jodhpur', stateSlug: 'rajasthan', stateName: 'Rajasthan', description: 'The Blue City crowned by the colossal ramparts of Mehrangarh Fort.', image: 'https://images.unsplash.com/photo-1572979203492-71448b22e743?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Mumbai', slug: 'mumbai', stateSlug: 'maharashtra', stateName: 'Maharashtra', description: 'The City of Dreams, historic colonial port and vibrant financial capital.', image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Aurangabad', slug: 'aurangabad', stateSlug: 'maharashtra', stateName: 'Maharashtra', description: 'Tourism capital of Maharashtra, gateway to world-renowned Ajanta & Ellora caves.', image: 'https://images.unsplash.com/photo-1600100397608-f010f443b593?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Alleppey', slug: 'alleppey', stateSlug: 'kerala', stateName: 'Kerala', description: 'Venice of the East, famed for interconnected palm-fringed backwater lagoons.', image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Munnar', slug: 'munnar', stateSlug: 'kerala', stateName: 'Kerala', description: 'Idyllic hill station nestled among rolling green tea carpeted slopes of Western Ghats.', image: 'https://images.unsplash.com/photo-1591081658714-f570fb66c29d?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Kochi', slug: 'kochi', stateSlug: 'kerala', stateName: 'Kerala', description: 'Historic Queen of Arabian Sea with Chinese fishing nets and colonial spice warehouses.', image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Mysuru', slug: 'mysuru', stateSlug: 'karnataka', stateName: 'Karnataka', description: 'City of Palaces, famed for festive illuminations, silk weaving, and sandalwood.', image: 'https://images.unsplash.com/photo-1590766940554-634a7ed41450?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Hampi', slug: 'hampi', stateSlug: 'karnataka', stateName: 'Karnataka', description: 'UNESCO World Heritage open-air museum of magnificent Vijayanagara Empire stone ruins.', image: 'https://images.unsplash.com/photo-1600100397608-f010f443b593?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Madurai', slug: 'madurai', stateSlug: 'tamil-nadu', stateName: 'Tamil Nadu', description: 'Ancient temple city designed in the shape of a blooming lotus around Meenakshi shrine.', image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Chennai', slug: 'chennai', stateSlug: 'tamil-nadu', stateName: 'Tamil Nadu', description: 'Coastal gateway to South India with classical arts and the expansive Marina Beach.', image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Kolkata', slug: 'kolkata', stateSlug: 'west-bengal', stateName: 'West Bengal', description: 'City of Joy, intellectual powerhouse characterized by colonial buildings and cultural fervor.', image: 'https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Darjeeling', slug: 'darjeeling', stateSlug: 'west-bengal', stateName: 'West Bengal', description: 'Queen of the Hills, renowned for champagne black tea and vistas of Mount Kanchenjunga.', image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Puri', slug: 'puri', stateSlug: 'odisha', stateName: 'Odisha', description: 'Spiritual seaside sanctuary of Lord Jagannath, holy coastal pilgrimage destination.', image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Konark', slug: 'konark', stateSlug: 'odisha', stateName: 'Odisha', description: 'Site of the magnificent 13th-century Sun Temple conceived as a cosmic chariot.', image: 'https://images.unsplash.com/photo-1620619767323-b95a89183081?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Guwahati', slug: 'guwahati', stateSlug: 'assam', stateName: 'Assam', description: 'Bustling metropolis on the Brahmaputra, gateway to the Kaziranga wild sanctuaries.', image: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Panaji', slug: 'panaji', stateSlug: 'goa', stateName: 'Goa', description: 'Goa’s charming capital with Latin Quarter Fontainhas, red-tiled roofs, and riverside promenade.', image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Amritsar', slug: 'amritsar', stateSlug: 'punjab', stateName: 'Punjab', description: 'Spiritual capital of Sikhism, guardian of the Golden Temple and rich culinary heritage.', image: 'https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Khajuraho', slug: 'khajuraho', stateSlug: 'madhya-pradesh', stateName: 'Madhya Pradesh', description: 'Ancient Chandela dynasty capital, famous for exquisite medieval sandstone sculptures.', image: 'https://images.unsplash.com/photo-1620619767323-b95a89183081?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'New Delhi', slug: 'new-delhi', stateSlug: 'delhi', stateName: 'Delhi', description: 'The national capital seat with majestic avenues, monuments, and historic gardens.', image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80', isActive: true },
  { name: 'Srinagar', slug: 'srinagar', stateSlug: 'jammu-and-kashmir', stateName: 'Jammu and Kashmir', description: 'Venice of Kashmir, graced with Dal Lake houseboats, shikaras, and royal Mughal terraces.', image: 'https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=800&q=80', isActive: true },
];

export const initialDestinations = [
  {
    name: 'Taj Mahal',
    slug: 'taj-mahal',
    state: 'uttar-pradesh',
    stateName: 'Uttar Pradesh',
    city: 'agra',
    cityName: 'Agra',
    category: 'heritage',
    categoryName: 'Heritage',
    shortDescription: 'The world-famous ivory-white marble mausoleum on the south bank of river Yamuna, an epitome of timeless love and UNESCO World Heritage Site.',
    description: 'Commissioned in 1632 by the Mughal emperor Shah Jahan to house the tomb of his favorite wife, Mumtaz Mahal, the Taj Mahal represents the pinnacle of Mughal architecture combining Indian, Persian, and Islamic artistic styles. The central tomb is surrounded by a four-part charbagh garden, reflecting pools, and red sandstone minarets.',
    historicalSignificance: 'Constructed over a span of 22 years by more than 20,000 artisans and masons under the guidance of chief architect Ustad Ahmad Lahori. It stands as the supreme architectural jewel of the Mughal empire in India.',
    culturalSignificance: 'Regarded internationally as the jewel of Muslim art in India and one of the universally admired masterpieces of the world’s heritage. It represents sublime poetic romance rendered in pure Makrana marble.',
    bestTimeToVisit: 'October to March (Winter months with pleasant cool weather and mist-free mornings)',
    recommendedDuration: '2 to 3 hours',
    openingHours: 'Sunrise to Sunset (Closed on Fridays for general visitors)',
    entryFee: '₹50 for Indian nationals, ₹1100 for Foreign tourists (Additional ₹200 for main mausoleum dome access)',
    location: 'Dharmapuri, Forest Colony, Tajganj, Agra, Uttar Pradesh 282001',
    mapUrl: 'https://maps.google.com/?q=Taj+Mahal+Agra',
    images: [
      'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1585506942812-e72b29cef752?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Agra Fort', 'Mehtab Bagh', 'Itmad-ud-Daulah (Baby Taj)', 'Fatehpur Sikri'],
    travelTips: [
      'Arrive right at sunrise to beat the crowd and experience soft golden light illuminating the marble.',
      'Leave tripods, power banks, and large bags in lockers at the gate as security screening is strict.',
      'Wear shoe covers provided with tickets before walking on the elevated marble terrace.',
    ],
    howToReach: {
      air: 'Kheria Airport Agra (12 km) or IGI Airport New Delhi (220 km connected via Yamuna Expressway).',
      train: 'Agra Cantt Railway Station (5 km), well connected by Gatimaan Express and Vande Bharat from Delhi.',
      road: 'Direct 3-hour expressway drive from New Delhi via Yamuna Expressway.',
    },
    verified: true,
    status: 'verified',
    isActive: true,
  },
  {
    name: 'Agra Fort',
    slug: 'agra-fort',
    state: 'uttar-pradesh',
    stateName: 'Uttar Pradesh',
    city: 'agra',
    cityName: 'Agra',
    category: 'forts',
    categoryName: 'Forts',
    shortDescription: 'The grand red sandstone imperial residence of Mughal emperors, overlooking the Yamuna with sweeping views of the Taj Mahal.',
    description: 'Agra Fort is a massive 16th-century fortress that served as the principal residence of the Mughal emperors until 1638. Built primarily by Emperor Akbar and expanded with white marble additions by Shah Jahan, the fort houses the Jahangiri Mahal, Diwan-i-Khas, Diwan-i-Aam, and Musamman Burj where Shah Jahan was confined in his final years.',
    historicalSignificance: 'Witnessed the rise and zenith of the Mughal dynasty. The fort underwent major sieges, including capture by Marathas and British forces during the 1857 war of independence.',
    culturalSignificance: 'A masterclass of Indo-Islamic architectural fusion, featuring Akbar’s robust Rajput-influenced brickwork alongside Shah Jahan’s delicate pietre dure marble pavilions.',
    bestTimeToVisit: 'October to March',
    recommendedDuration: '2 hours',
    openingHours: '6:00 AM to 6:00 PM every day',
    entryFee: '₹50 for Indian nationals, ₹650 for Foreign nationals (Free for children below 15)',
    location: 'Agra Fort, Rakabganj, Agra, Uttar Pradesh 282003',
    mapUrl: 'https://maps.google.com/?q=Agra+Fort+Agra',
    images: [
      'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1585506942812-e72b29cef752?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Taj Mahal', 'Itmad-ud-Daulah', 'Jama Masjid Agra', 'Kinari Bazaar'],
    travelTips: [
      'Hire an authorized government guide to understand the fascinating palace acoustics and escape tunnels.',
      'Check out the octagonal Musamman Burj tower where Shah Jahan gazed upon the Taj Mahal in captivity.',
    ],
    howToReach: {
      air: 'Kheria Airport Agra (6 km).',
      train: 'Agra Fort Railway Station is located just 1 km from the fort entrance.',
      road: 'Accessible via auto-rickshaw or taxi throughout Agra city.',
    },
    verified: true,
    status: 'published',
    isActive: true,
  },
  {
    name: 'Kashi Vishwanath & Varanasi Ghats',
    slug: 'kashi-vishwanath-varanasi-ghats',
    state: 'uttar-pradesh',
    stateName: 'Uttar Pradesh',
    city: 'varanasi',
    cityName: 'Varanasi',
    category: 'religious',
    categoryName: 'Religious',
    shortDescription: 'The eternal spiritual soul of India, where sacred Ganga steps host mesmerizing evening aarti ceremonies and ancient Shiva worship.',
    description: 'Varanasi, or Kashi, is regarded as one of the holiest pilgrim destinations for Hindus. The newly expanded Kashi Vishwanath Dham corridor connects the sanctum sanctorum of the Jyotirlinga directly with the river Ganga. Across 84 ancient ghats including Dashashwamedh, Assi, and Manikarnika, pilgrims and seekers witness continuous cycles of life, devotion, and liberation.',
    historicalSignificance: 'Described by Mark Twain as older than history, older than tradition, older even than legend. The Golden Temple was rebuilt by Queen Ahilyabai Holkar of Indore in 1780.',
    culturalSignificance: 'The philosophical cradle of Hinduism, Buddhism (Sarnath lies 10 km away), classical Banaras Gharana music, and handwoven Banarasi silk sarees.',
    bestTimeToVisit: 'November to February (Pleasant winter climate; ideal for dawn boat rides)',
    recommendedDuration: 'Half day to full day',
    openingHours: 'Temple: 3:00 AM to 11:00 PM; Ghats open 24 hours',
    entryFee: 'Free entry for general darshan; specialized Sugam Darshan passes available',
    location: 'Lahori Tola, Varanasi, Uttar Pradesh 221001',
    mapUrl: 'https://maps.google.com/?q=Kashi+Vishwanath+Temple+Varanasi',
    images: [
      'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1571536802807-30451e3955d8?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Dashashwamedh Ghat', 'Sarnath Buddhist Stupa', 'Assi Ghat', 'Ramnagar Fort'],
    travelTips: [
      'Book a sunrise rowboat ride from Assi to Dashashwamedh Ghat for serene photography.',
      'Arrive by 5:30 PM at Dashashwamedh Ghat to secure a good viewing spot for the grand Ganga Aarti.',
      'Dress modestly and leave mobile phones/leather items at cloakrooms before entering the temple.',
    ],
    howToReach: {
      air: 'Lal Bahadur Shastri International Airport Varanasi (25 km).',
      train: 'Varanasi Junction (Cantt) or Banaras Railway Station (4-6 km).',
      road: 'Extensive bus and highway connectivity via NH 19.',
    },
    verified: true,
    status: 'verified',
    isActive: true,
  },
  {
    name: 'Amer Fort',
    slug: 'amer-fort',
    state: 'rajasthan',
    stateName: 'Rajasthan',
    city: 'jaipur',
    cityName: 'Jaipur',
    category: 'forts',
    categoryName: 'Forts',
    shortDescription: 'A majestic hill-top Rajput stronghold featuring pink and yellow sandstone, the shimmering Sheesh Mahal, and Maota Lake views.',
    description: 'Perched high on the Cheel ka Teela (Hill of Eagles), Amer Fort was built by Raja Man Singh I in 1592. It is renowned for its artistic Rajput architectural elements. Highlights include the Diwan-e-Aam, Sukh Niwas with natural water-cooled breezes, and the breathtaking Sheesh Mahal (Mirror Palace) inlaid with thousands of imported Belgian glass mirrors.',
    historicalSignificance: 'Capital of the Kachwaha Rajputs before Maharaja Sawai Jai Singh II founded Jaipur in 1727. Amer was virtually unbreachable owing to subterranean passages connecting it with Jaigarh Fort.',
    culturalSignificance: 'Showcases how Rajput rulers gracefully combined Hindu courtyard aesthetics with Mughal ornamental finesse.',
    bestTimeToVisit: 'October to March',
    recommendedDuration: '3 to 4 hours',
    openingHours: '8:00 AM to 5:30 PM, Evening Sound & Light Show: 6:30 PM to 9:00 PM',
    entryFee: '₹100 for Indian nationals, ₹500 for Foreign nationals',
    location: 'Devisinghpura, Amer, Jaipur, Rajasthan 302001',
    mapUrl: 'https://maps.google.com/?q=Amer+Fort+Jaipur',
    images: [
      'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Jaigarh Fort', 'Nahargarh Fort', 'Jal Mahal', 'Panna Meena ka Kund'],
    travelTips: [
      'Walk up the cobbled ramp or take an authorized electric jeep rather than animal rides.',
      'Stay for the evening sound and light show that dramatizes Jaipur’s dynastic legends.',
      'Combine your visit with the stepwell Panna Meena ka Kund just 1 km away.',
    ],
    howToReach: {
      air: 'Jaipur International Airport (22 km).',
      train: 'Jaipur Junction Railway Station (13 km).',
      road: 'Located on the Delhi-Jaipur highway, 11 km north of Jaipur center.',
    },
    verified: true,
    status: 'verified',
    isActive: true,
  },
  {
    name: 'Jaipur City Palace & Hawa Mahal',
    slug: 'jaipur-city-palace-hawa-mahal',
    state: 'rajasthan',
    stateName: 'Rajasthan',
    city: 'jaipur',
    cityName: 'Jaipur',
    category: 'heritage',
    categoryName: 'Heritage',
    shortDescription: 'The royal seat of the Maharaja of Jaipur featuring courtyards, Peacock Gate, and the iconic 953-casement Palace of Winds.',
    description: 'Located in the heart of the Old City of Jaipur, the City Palace complex was established by Maharaja Sawai Jai Singh II. It encompasses Chandra Mahal and Mubarak Mahal along with museums housing royal costumes and weaponry. Just outside stands Hawa Mahal, a honeycomb façade with 953 jharokhas built to allow royal women to observe street festivities unobserved.',
    historicalSignificance: 'Built alongside the planned founding of Jaipur city in 1727 following ancient Vastu Shastra urban principles.',
    culturalSignificance: 'Celebrated for its four inner courtyard gates representing the four seasons, particularly the Peacock Gate symbolizing autumn.',
    bestTimeToVisit: 'October to March',
    recommendedDuration: '2 to 3 hours',
    openingHours: '9:30 AM to 5:00 PM daily',
    entryFee: '₹200 for Indian nationals, ₹700 for Foreign visitors (City Palace)',
    location: 'Tulsi Marg, Gangori Bazaar, J.D.A. Market, Jaipur, Rajasthan 302002',
    mapUrl: 'https://maps.google.com/?q=City+Palace+Jaipur',
    images: [
      'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Jantar Mantar Observatory', 'Hawa Mahal', 'Bapu Bazaar', 'Albert Hall Museum'],
    travelTips: [
      'Get a composite ticket covering City Palace, Jantar Mantar, and Hawa Mahal to save time.',
      'Visit rooftop cafes opposite Hawa Mahal for panoramic street-level photography of the façade.',
    ],
    howToReach: {
      air: 'Jaipur International Airport (12 km).',
      train: 'Jaipur Junction Railway Station (4 km).',
      road: 'Easily reached via Jaipur Metro (Badi Chaupar station).',
    },
    verified: true,
    status: 'published',
    isActive: true,
  },
  {
    name: 'Mehrangarh Fort',
    slug: 'mehrangarh-fort',
    state: 'rajasthan',
    stateName: 'Rajasthan',
    city: 'jodhpur',
    cityName: 'Jodhpur',
    category: 'forts',
    categoryName: 'Forts',
    shortDescription: 'One of the largest fortresses in India, rising 400 feet above the Blue City of Jodhpur with sheer impregnable walls.',
    description: 'Commissioned in 1459 by Rao Jodha, Mehrangarh Fort stands on an isolated cliff known as Bhakurcheeria. Within its walls are splendid palaces including Moti Mahal, Phool Mahal, and Sheesh Mahal, along with one of Rajasthan’s finest museums showcasing royal palanquins, turbans, and miniatures.',
    historicalSignificance: 'Survived numerous sieges by Mughal and Jaipur armies; cannonball marks are still preserved at the historic Dedh Kamgra Gate.',
    culturalSignificance: 'Host to the prestigious Rajasthan International Folk Festival (RIFF) and World Sacred Spirit Festival.',
    bestTimeToVisit: 'October to March',
    recommendedDuration: '3 hours',
    openingHours: '9:00 AM to 5:00 PM',
    entryFee: '₹100 for Indian nationals, ₹600 for Foreign visitors (includes audio guide)',
    location: 'Fort Rd, Jodhpur, Rajasthan 342006',
    mapUrl: 'https://maps.google.com/?q=Mehrangarh+Fort+Jodhpur',
    images: [
      'https://images.unsplash.com/photo-1572979203492-71448b22e743?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Jaswant Thada', 'Umaid Bhawan Palace', 'Clock Tower & Sardar Market', 'Mandore Gardens'],
    travelTips: [
      'Opt for the zip-lining (Flying Fox) tour around the fort ramparts and moat for an exhilarating perspective.',
      'Walk to the ramparts at sunset to photograph the sea of blue houses stretching out below.',
    ],
    howToReach: {
      air: 'Jodhpur Civil Airport (8 km).',
      train: 'Jodhpur Junction Railway Station (3 km).',
      road: 'Frequent taxis and autorickshaws climb the winding fort hill road.',
    },
    verified: true,
    status: 'published',
    isActive: true,
  },
  {
    name: 'Udaipur City Palace & Lake Pichola',
    slug: 'udaipur-city-palace-lake-pichola',
    state: 'rajasthan',
    stateName: 'Rajasthan',
    city: 'udaipur',
    cityName: 'Udaipur',
    category: 'heritage',
    categoryName: 'Heritage',
    shortDescription: 'The crown jewel of Rajasthan’s lake city, a grand granite and marble lakeside complex overlooking Lake Pichola and Jag Mandir.',
    description: 'Begun in 1559 by Maharana Udai Singh II, the City Palace was augmented by successive Maharanas over 400 years to become Rajasthan’s largest palace complex. Featuring balconies, cupolas, towers, and inlaid mirror work, it offers panoramic vistas across the serene waters of Lake Pichola to the Lake Palace (Taj Lake Palace).',
    historicalSignificance: 'Seat of the Mewar Kingdom, the only Rajput state that stubbornly resisted total Mughal vassalage under heroes like Maharana Pratap.',
    culturalSignificance: 'Epitomizes Rajasthani courtly romance and architectural brilliance with museum collections of silver artifacts and miniature art.',
    bestTimeToVisit: 'September to March',
    recommendedDuration: '3 to 4 hours',
    openingHours: '9:00 AM to 5:30 PM; Boat rides till 6:00 PM',
    entryFee: '₹300 for adults, ₹100 for children; Boat cruise ₹450-₹800',
    location: 'Old City, Udaipur, Rajasthan 313001',
    mapUrl: 'https://maps.google.com/?q=City+Palace+Udaipur',
    images: [
      'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Lake Pichola Boat Cruise', 'Jagdish Temple', 'Saheliyon-ki-Bari', 'Bagore Ki Haveli'],
    travelTips: [
      'Book the sunset boat cruise to Jag Mandir island for reflections of the palace lit up in amber hues.',
      'Attend the evening Dharohar folk dance show at nearby Bagore Ki Haveli at 7:00 PM.',
    ],
    howToReach: {
      air: 'Maharana Pratap Airport Udaipur (24 km).',
      train: 'Udaipur City Railway Station (3 km).',
      road: 'Well connected by national highways to Ahmedabad (250 km) and Jaipur (390 km).',
    },
    verified: true,
    status: 'verified',
    isActive: true,
  },
  {
    name: 'Gateway of India',
    slug: 'gateway-of-india',
    state: 'maharashtra',
    stateName: 'Maharashtra',
    city: 'mumbai',
    cityName: 'Mumbai',
    category: 'historical',
    categoryName: 'Historical',
    shortDescription: 'The majestic basalt arch monument overlooking Mumbai Harbour, where India bade farewell to the last British military troops.',
    description: 'Erected in the Indo-Saracenic style with yellow basalt, the Gateway of India was built to commemorate the 1911 landing of King George V and Queen Mary. Today it stands as Mumbai’s most iconic civic monument, facing the historic Taj Mahal Palace Hotel and serving as the embarkation point for ferries to Elephanta Caves.',
    historicalSignificance: 'On 28 February 1948, the Somerset Light Infantry marched through the archway to board ships, marking the symbolic final exit of British forces from independent India.',
    culturalSignificance: 'The premier public gathering space of Mumbai, filled with street photographers, balloon vendors, tourists, and sea breezes.',
    bestTimeToVisit: 'November to February (Pleasant winter breeze along the Arabian Sea)',
    recommendedDuration: '1 hour',
    openingHours: 'Open 24 hours (Best visited between 6:00 AM and 10:00 PM)',
    entryFee: 'Free entry (Ferry to Elephanta ticketed separately)',
    location: 'Apollo Bandar, Colaba, Mumbai, Maharashtra 400001',
    mapUrl: 'https://maps.google.com/?q=Gateway+of+India+Mumbai',
    images: [
      'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['The Taj Mahal Palace Hotel', 'Colaba Causeway', 'Elephanta Island Caves', 'Marine Drive'],
    travelTips: [
      'Take the ferry from the jetty to Elephanta Caves in the morning before noon heat.',
      'Walk to nearby Marine Drive for the famous "Queen’s Necklace" seaside sunset view.',
    ],
    howToReach: {
      air: 'Chhatrapati Shivaji Maharaj International Airport (25 km).',
      train: 'Chhatrapati Shivaji Maharaj Terminus (CSMT) or Churchgate (2.5 km).',
      road: 'Easily accessible by Mumbai black-and-yellow taxis and city buses.',
    },
    verified: true,
    status: 'published',
    isActive: true,
  },
  {
    name: 'Ellora Caves',
    slug: 'ellora-caves',
    state: 'maharashtra',
    stateName: 'Maharashtra',
    city: 'aurangabad',
    cityName: 'Aurangabad',
    category: 'heritage',
    categoryName: 'Heritage',
    shortDescription: 'World’s largest monolithic rock-cut monument complex, featuring Cave 16 Kailasa Temple carved out of a single basalt cliff.',
    description: 'Ellora consists of 34 major monasteries and temples excavated side by side out of the Charanandri hills between the 6th and 10th centuries CE. It is globally unparalleled because Buddhist, Hindu, and Jain monuments co-exist in harmony. Cave 16, the Kailasa Temple, is a mind-boggling engineering marvel carved top-down from 200,000 tonnes of basalt rock.',
    historicalSignificance: 'Built during the Rashtrakuta and Yadava dynasties, representing religious tolerance and apex ancient Indian stone craftsmanship.',
    culturalSignificance: 'UNESCO World Heritage Site embodying artistic syncretism and supreme civilizational engineering acumen.',
    bestTimeToVisit: 'October to March (Monsoon July-September is also lush with nearby waterfalls)',
    recommendedDuration: '4 to 5 hours',
    openingHours: '6:00 AM to 6:00 PM (Closed on Tuesdays)',
    entryFee: '₹40 for Indian nationals, ₹600 for Foreign visitors',
    location: 'Ellora, Verul, Aurangabad District, Maharashtra 431102',
    mapUrl: 'https://maps.google.com/?q=Ellora+Caves+Aurangabad',
    images: [
      'https://images.unsplash.com/photo-1600100397608-f010f443b593?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Ajanta Caves', 'Grishneshwar Jyotirlinga', 'Daulatabad Fort', 'Bibi Ka Maqbara'],
    travelTips: [
      'Start early at Cave 16 (Kailasa Temple) to spend quality time exploring its multi-storey corridors before midday heat.',
      'Wear sturdy walking shoes with grip; the basalt paths and steps can be slick.',
    ],
    howToReach: {
      air: 'Chhatrapati Sambhajinagar (Aurangabad) Airport (35 km).',
      train: 'Aurangabad Railway Station (30 km).',
      road: '30 km drive from Aurangabad along NH 52.',
    },
    verified: true,
    status: 'verified',
    isActive: true,
  },
  {
    name: 'Ajanta Caves',
    slug: 'ajanta-caves',
    state: 'maharashtra',
    stateName: 'Maharashtra',
    city: 'aurangabad',
    cityName: 'Aurangabad (Chhatrapati Sambhajinagar)',
    category: 'heritage',
    categoryName: 'Heritage',
    shortDescription: 'UNESCO World Heritage ensemble of 30 rock-cut Buddhist cave monuments carved into a sheer horseshoe-shaped basalt cliff above the Waghur River, world-celebrated for tempera mural masterpieces including Bodhisattva Padmapani.',
    description: 'Carved over two distinct civilizational epochs between the 2nd century BCE and the 5th century CE, the 30 rock-cut caves of Ajanta represent the pinnacle of ancient Indian classical Buddhist art. The site comprises both Chaitya-grihas (prayer and stupa assembly halls, notably Caves 9, 10, 19, and 26) and Viharas (monastic residential complexes with central pillared courtyards and meditation cells). The earlier Hinayana phase was constructed during the Satavahana era, while the magnificent second floruit arose under the royal patronage of the Vakataka dynasty under King Harishena (c. 460–480 CE). The world-renowned murals—executed in dry fresco-tempera over rock plaster incorporating clay, organic fibers, rice husks, and precious minerals such as lapis lazuli from Badakhshan and malachite—depict Jataka tales, the life of Gautama Buddha, celestial nymphs (apsaras), and royal courtly processions with unmatched emotional subtlety and three-dimensional shading.',
    historicalSignificance: 'Served as an essential monastic retreat and philosophical university positioned along ancient trade routes linking the Deccan plateau with western Indian ports. Following the sudden collapse of the Vakataka dynasty, the site was abandoned and swallowed by dense jungle until 28 April 1819, when a young British officer, Captain John Smith of the 28th Madras Cavalry, stumbled upon the entrance arch of Cave 10 while tracking a tiger across the Waghur ravine. Smith scratched his name onto a pillar in Cave 10, an inscription that remains preserved today.',
    culturalSignificance: 'Universally hailed as the foundational masterpiece of Asian pictorial art. The sublime depiction of Bodhisattva Padmapani (the Lotus-Bearer) in Cave 1, with his sorrowful, compassionate eyes downcast upon earthly suffering, is recognized as one of the highest achievements of spiritual figurative art in human history, directly inspiring Buddhist murals across Sri Lanka (Sigiriya), Central Asia (Dunhuang/Mogao), and classical Japanese art at Horyu-ji.',
    bestTimeToVisit: 'October to March (Crisp, comfortable winter days; late monsoon from July to September also surrounds the horseshoe canyon with cascading waterfalls and lush green foliage)',
    recommendedDuration: '4 to 5 hours',
    openingHours: '9:00 AM to 5:00 PM (Strictly closed on Mondays)',
    entryFee: '₹40 for Indian nationals & SAARC/BIMSTEC visitors; ₹600 for Foreign tourists (Free for children under 15; ₹25 ASI camera fee)',
    location: 'Ajanta Caves Road, Lenapur, Aurangabad District (Chhatrapati Sambhajinagar), Maharashtra 431117',
    mapUrl: 'https://maps.google.com/?q=Ajanta+Caves+Maharashtra',
    images: [
      '/images/ajanta/horseshoe-gorge.jpg',
      '/images/ajanta/padmapani-bodhisattva.jpg',
      '/images/ajanta/cave-19-chaitya.jpg',
      '/images/ajanta/cave-26-reclining-buddha.jpg',
    ],
    nearbyAttractions: [
      'Ellora Caves & Kailasa Temple',
      'Waghur River Gorge & View Point',
      'Daulatabad (Devagiri) Fort',
      'Grishneshwar Jyotirlinga Temple',
    ],
    travelTips: [
      'Flash photography is strictly prohibited inside the caves to prevent ultraviolet damage to the 1,500-year-old organic pigments. Carry a small pocket torch to observe shaded reliefs.',
      'Visitors must park at the T-point tourist center and board the designated green eco-friendly shuttle bus for the final 4 km approach to the cave ticket counter.',
      'Climb up to the "Viewpoint" plateau opposite the gorge for the legendary postcard view where Captain John Smith first gazed upon the entire crescent ravine.',
      'Do not touch or lean against the painted plaster surfaces; several caves feature protective glass barriers installed by the Archaeological Survey of India.',
    ],
    howToReach: {
      air: 'Chhatrapati Sambhajinagar (Aurangabad) Airport (IXU, 100 km) and Jalgaon Airport (60 km), with daily direct flights from Mumbai, Delhi, and Hyderabad.',
      train: 'Jalgaon Junction (60 km) is the closest mainline rail hub on the Central Railway; Aurangabad Railway Station (100 km) connects to Mumbai and Pune.',
      road: 'Scenic 2.5-hour highway drive from Aurangabad along NH 753F. Regular air-conditioned MSRTC tourist coaches and private taxis are easily booked in Aurangabad.',
    },
    verified: true,
    status: 'verified',
    isActive: true,
  },
  {
    name: 'Kerala Backwaters & Alleppey Houseboats',
    slug: 'kerala-backwaters-alleppey',
    state: 'kerala',
    stateName: 'Kerala',
    city: 'alleppey',
    cityName: 'Alleppey',
    category: 'nature',
    categoryName: 'Nature',
    shortDescription: 'A tranquil labyrinth of palm-lined canals, lagoons, and emerald paddy fields navigated on traditional Kettuvallam houseboats.',
    description: 'The Kerala Backwaters are a network of brackish lagoons and lakes lying parallel to the Arabian Sea coast. In Alleppey (Alappuzha), visitors board thatched-roof Kettuvallam boats converted into luxury floating homes to cruise past village life, coir workers, kingfishers, and endless coconut groves.',
    historicalSignificance: 'Originally used to transport rice, spices, and coir from remote coastal villages to regional trading ports before road transport emerged.',
    culturalSignificance: 'Site of the world-famous Nehru Trophy Snake Boat Race held annually on Punnamada Lake on the second Saturday of August.',
    bestTimeToVisit: 'October to February (Cool winter) or June-August (Monsoon lushness & boat races)',
    recommendedDuration: 'Overnight stay on houseboat or 4-hour day cruise',
    openingHours: 'Cruises operate from 11:30 AM to 5:30 PM (Boats anchor overnight)',
    entryFee: 'Houseboat rental varies from ₹7,000 to ₹25,000 per night depending on luxury category',
    location: 'Punnamada Jetty, Finishing Point, Alappuzha, Kerala 688013',
    mapUrl: 'https://maps.google.com/?q=Alleppey+Backwaters+Kerala',
    images: [
      'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Marari Beach', 'Vembanad Lake', 'Kumarakom Bird Sanctuary', 'Krishnapuram Palace'],
    travelTips: [
      'Opt for certified DTPC houseboats to ensure ethical waste treatment and proper safety gear.',
      'Savor freshly prepared Karimeen Pollichathu (pearl spot fish wrapped in banana leaf) cooked on board.',
    ],
    howToReach: {
      air: 'Cochin International Airport (85 km).',
      train: 'Alappuzha Railway Station (4 km).',
      road: 'Directly linked via NH 66 from Kochi (55 km) and Trivandrum (150 km).',
    },
    verified: true,
    status: 'verified',
    isActive: true,
  },
  {
    name: 'Munnar Tea Estates & Anamudi',
    slug: 'munnar-tea-estates',
    state: 'kerala',
    stateName: 'Kerala',
    city: 'munnar',
    cityName: 'Munnar',
    category: 'hill-stations',
    categoryName: 'Hill Stations',
    shortDescription: 'Verdant rolling tea plantations perched at 1,600 meters in the Western Ghats, home to the endangered Nilgiri Tahr.',
    description: 'Located at the confluence of three mountain streams (Mudhirapuzha, Nallathanni, and Kundaly), Munnar was the favored summer resort of the British government in South India. It features manicured emerald tea plantations stretching into mist-covered peaks, Eravikulam National Park, and Anamudi, South India’s highest summit.',
    historicalSignificance: 'Tea cultivation was introduced in the late 19th century by pioneering Scottish planters under the Kannan Devan Hills Produce Company.',
    culturalSignificance: 'Famous for the rare Neelakurinji flower that blooms once every twelve years, transforming hillsides into an ocean of violet-blue.',
    bestTimeToVisit: 'September to March (Crisp mountain air and blooming orchids)',
    recommendedDuration: '2 to 3 days',
    openingHours: 'Tea gardens: Daylight hours; Eravikulam Park: 7:30 AM to 4:00 PM',
    entryFee: 'Park entry ₹200 for Indian nationals, ₹500 for Foreign visitors',
    location: 'Idukki District, Munnar, Kerala 685612',
    mapUrl: 'https://maps.google.com/?q=Munnar+Tea+Gardens+Kerala',
    images: [
      'https://images.unsplash.com/photo-1591081658714-f570fb66c29d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Eravikulam National Park', 'Mattupetty Dam', 'Top Station', 'Tata Tea Museum'],
    travelTips: [
      'Carry light woolens even in summer as evenings turn chilly in high-altitude tea valleys.',
      'Book Eravikulam National Park tickets online early in the morning to see wild Nilgiri Tahr.',
    ],
    howToReach: {
      air: 'Cochin International Airport (110 km).',
      train: 'Aluva Railway Station (115 km) or Ernakulam Junction (130 km).',
      road: 'Scenic mountain road drive via NH 85 with waterfalls along the way.',
    },
    verified: true,
    status: 'published',
    isActive: true,
  },
  {
    name: 'Hampi Ruins & Virupaksha Temple',
    slug: 'hampi-ruins-virupaksha-temple',
    state: 'karnataka',
    stateName: 'Karnataka',
    city: 'hampi',
    cityName: 'Hampi',
    category: 'heritage',
    categoryName: 'Heritage',
    shortDescription: 'The surreal boulder-strewn capital of the Vijayanagara Empire, featuring the stone chariot, musical pillars, and sacred Tungabhadra.',
    description: 'Hampi is a UNESCO World Heritage Site in northern Karnataka nestled along the banks of the Tungabhadra River. It preserves the ruins of Vijayanagara, one of the largest and richest medieval cities in the world in the 15th century. Highlights include the still-active Virupaksha Temple, the iconic stone chariot of Vittala Temple, and Lotus Mahal.',
    historicalSignificance: 'Described by Portuguese and Persian chroniclers as rivaling Rome in wealth and grandeur until its tragic sack in 1565 after the Battle of Talikota.',
    culturalSignificance: 'Identified with Kishkindha, the mythical monkey kingdom mentioned in the epic Ramayana.',
    bestTimeToVisit: 'October to February (Pleasant winter, ideal for cycling across monuments)',
    recommendedDuration: '2 to 3 days',
    openingHours: 'Monuments open 6:00 AM to 6:00 PM; Virupaksha temple opens at 6:00 AM',
    entryFee: '₹40 for Indian nationals, ₹600 for Foreign visitors (Ticket covers Vittala & Zenana enclosure)',
    location: 'Hampi, Vijayanagara District, Karnataka 583239',
    mapUrl: 'https://maps.google.com/?q=Hampi+Karnataka',
    images: [
      'https://images.unsplash.com/photo-1600100397608-f010f443b593?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Vittala Temple Stone Chariot', 'Matanga Hill Sunrise', 'Lotus Mahal', 'Sanapur Lake'],
    travelTips: [
      'Rent a bicycle or moped to explore the vast 41 sq km open archaeological landscape at your own pace.',
      'Climb Matanga Hill before dawn for an unforgettable panoramic 360-degree sunrise over the boulder landscape.',
    ],
    howToReach: {
      air: 'Jindal Vidyanagar Airport Bellary (35 km) or Hubballi Airport (140 km).',
      train: 'Hosapete Junction (Hospet) is just 13 km away.',
      road: 'Overnight luxury sleeper buses available from Bengaluru (340 km) and Goa (320 km).',
    },
    verified: true,
    status: 'verified',
    isActive: true,
  },
  {
    name: 'Mysore Palace (Amba Vilas)',
    slug: 'mysore-palace-amba-vilas',
    state: 'karnataka',
    stateName: 'Karnataka',
    city: 'mysuru',
    cityName: 'Mysuru',
    category: 'heritage',
    categoryName: 'Heritage',
    shortDescription: 'The magnificent Indo-Saracenic royal seat of the Wadiyar dynasty, illuminated by 100,000 incandescent bulbs on festive weekends.',
    description: 'Designed by British architect Henry Irwin and completed in 1912, Mysore Palace is one of India’s most visited monuments. The three-story stone structure with marble domes and a 145-foot five-story tower boasts ornate mahogany ceilings, stained glass domes, cast iron pillars, and the legendary golden royal throne.',
    historicalSignificance: 'Seat of the Kingdom of Mysore, ruled by the Wadiyars who patronized music, astronomy, and modern educational institutions in South India.',
    culturalSignificance: 'Centerpiece of the world-renowned 10-day Mysuru Dasara festival, culminating in the grand Jamboo Savari elephant procession carrying goddess Chamundeshwari.',
    bestTimeToVisit: 'October to March (Dasara in September/October is peak festival season)',
    recommendedDuration: '2 to 3 hours',
    openingHours: '10:00 AM to 5:30 PM (Illumination on Sundays and public holidays 7:00 PM to 7:45 PM)',
    entryFee: '₹100 for Indian adults, ₹300 for Foreign tourists (Audio guide included)',
    location: 'Sayyaji Rao Rd, Agrahara, Chamrajpura, Mysuru, Karnataka 570001',
    mapUrl: 'https://maps.google.com/?q=Mysore+Palace+Mysuru',
    images: [
      'https://images.unsplash.com/photo-1590766940554-634a7ed41450?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Chamundi Hill Temple', 'Brindavan Gardens', 'St. Philomena’s Cathedral', 'Jaganmohan Art Gallery'],
    travelTips: [
      'Visit on a Sunday evening around 6:45 PM to witness the breathtaking sight of 100,000 bulbs illuminating simultaneously.',
      'Footwear must be deposited at the palace counter before stepping inside the interior galleries.',
    ],
    howToReach: {
      air: 'Mysuru Domestic Airport (10 km) or Kempegowda International Airport Bengaluru (180 km).',
      train: 'Mysuru Junction Railway Station (2 km).',
      road: 'High-speed 10-lane expressway connects Bengaluru to Mysuru in under 2 hours.',
    },
    verified: true,
    status: 'verified',
    isActive: true,
  },
  {
    name: 'Meenakshi Amman Temple',
    slug: 'meenakshi-amman-temple',
    state: 'tamil-nadu',
    stateName: 'Tamil Nadu',
    city: 'madurai',
    cityName: 'Madurai',
    category: 'temples',
    categoryName: 'Temples',
    shortDescription: 'An ancient Dravidian spiritual citadel featuring 14 towering gopurams encrusted with thousands of brightly colored mythological sculptures.',
    description: 'Located in the historic temple city of Madurai along the Vaigai River, Meenakshi Amman Temple is dedicated to Meenakshi (an avatar of Parvati) and her consort Sundareswarar (Shiva). The complex features the famous Hall of Thousand Pillars (each pillar carved from single granite rock), the sacred Golden Lotus tank, and continuous devotional rituals.',
    historicalSignificance: 'Mentioned in Sangam literature over 2,500 years ago; the present structure was rebuilt and expanded by the Nayak rulers between 1560 and 1655.',
    culturalSignificance: 'One of the few major Hindu temples where the goddess is revered as the primary sovereign deity of the city.',
    bestTimeToVisit: 'October to March',
    recommendedDuration: '2 to 3 hours',
    openingHours: '5:00 AM to 12:30 PM and 4:00 PM to 10:00 PM daily',
    entryFee: 'Free general darshan; ₹50 for special queue; ₹5 for Thousand Pillar Hall museum',
    location: 'Madurai Main, Madurai, Tamil Nadu 625001',
    mapUrl: 'https://maps.google.com/?q=Meenakshi+Temple+Madurai',
    images: [
      'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Thirumalai Nayakkar Palace', 'Gandhi Memorial Museum', 'Vaigai River Dam', 'Alagar Kovil'],
    travelTips: [
      'Witness the night ceremony (around 9:30 PM) where the deity Sundareswarar is carried to Meenakshi’s shrine in a silver palanquin.',
      'Mobile phones and cameras are strictly banned inside the main sanctum corridors.',
    ],
    howToReach: {
      air: 'Madurai Airport (12 km).',
      train: 'Madurai Junction Railway Station (1.5 km).',
      road: 'Extensive express bus network connecting to Chennai, Bengaluru, and Kochi.',
    },
    verified: true,
    status: 'verified',
    isActive: true,
  },
  {
    name: 'Konark Sun Temple',
    slug: 'konark-sun-temple',
    state: 'odisha',
    stateName: 'Odisha',
    city: 'konark',
    cityName: 'Konark',
    category: 'heritage',
    categoryName: 'Heritage',
    shortDescription: 'The 13th-century monumental stone chariot of the Sun God Surya, featuring 24 intricately carved stone sundial wheels.',
    description: 'Built in the 13th century by King Narasimhadeva I of the Eastern Ganga dynasty, the Konark Sun Temple was designed as an enormous cosmic chariot with 24 wheels pulled by seven galloping stone horses. The wheels function as precise sundials down to minutes. The stone carvings illustrate daily life, celestial musicians, and mythic motifs in Kalinga architecture.',
    historicalSignificance: 'European sailors called it the "Black Pagoda" as its dark towering profile served as an essential navigation beacon in the Bay of Bengal.',
    culturalSignificance: 'Rabindranath Tagore wrote: "Here the language of stone surpasses the language of human art." Host to the prestigious Konark Dance Festival.',
    bestTimeToVisit: 'October to March',
    recommendedDuration: '2 to 3 hours',
    openingHours: '6:00 AM to 8:00 PM',
    entryFee: '₹40 for Indian nationals, ₹600 for Foreign visitors',
    location: 'Konark, Puri District, Odisha 752111',
    mapUrl: 'https://maps.google.com/?q=Konark+Sun+Temple+Odisha',
    images: [
      'https://images.unsplash.com/photo-1620619767323-b95a89183081?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Chandrabhaga Beach', 'ASI Site Museum', 'Puri Jagannath Temple', 'Chilika Lake'],
    travelTips: [
      'Hire an authorized ASI guide who can demonstrate how the shadows on the spokes tell the exact time of day.',
      'Visit nearby Chandrabhaga Beach just 3 km away for coastal breezes after exploring the temple.',
    ],
    howToReach: {
      air: 'Biju Patnaik International Airport Bhubaneswar (65 km).',
      train: 'Puri Railway Station (35 km) or Bhubaneswar (65 km).',
      road: 'Scenic marine drive connects Puri to Konark along the sea coast.',
    },
    verified: true,
    status: 'verified',
    isActive: true,
  },
  {
    name: 'Puri Jagannath Temple & Beach',
    slug: 'puri-jagannath-temple',
    state: 'odisha',
    stateName: 'Odisha',
    city: 'puri',
    cityName: 'Puri',
    category: 'religious',
    categoryName: 'Religious',
    shortDescription: 'One of the Char Dham pilgrimage sanctuaries, home to Lord Jagannath and the world-famous colossal Ratha Yatra chariot procession.',
    description: 'Standing on the Bay of Bengal coast, the 12th-century Jagannath Temple is sacred to Vaishnava traditions. Lord Jagannath, along with Balabhadra and Subhadra, is worshiped here in distinctive carved neem wood forms. The temple kitchen (Ananda Bazar) is believed to be the world’s largest traditional earthen cooking facility.',
    historicalSignificance: 'Built by King Anantavarman Chodaganga of the Eastern Ganga dynasty; preserves ancient mystery surrounding the flag fluttering contrary to the wind.',
    culturalSignificance: 'Epicenter of the annual Ratha Yatra, where massive multi-story wooden chariots are pulled by hundreds of thousands of ecstatic devotees.',
    bestTimeToVisit: 'October to February (Ratha Yatra occurs in June/July)',
    recommendedDuration: '2 to 4 hours',
    openingHours: '5:00 AM to 11:00 PM',
    entryFee: 'Free entry for practicing Hindus; others can view the temple spire from Raghunandan Library roof',
    location: 'Grand Rd, Puri, Odisha 752001',
    mapUrl: 'https://maps.google.com/?q=Jagannath+Temple+Puri',
    images: [
      'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Golden Beach Puri (Blue Flag Certified)', 'Konark Sun Temple', 'Raghurajpur Crafts Village', 'Chilika Lake'],
    travelTips: [
      'Taste the divine Mahaprasad (Khaja and sacred bhog) cooked inside seven stacked earthen pots.',
      'Take an evening stroll at the Blue Flag certified Golden Beach along Marine Drive.',
    ],
    howToReach: {
      air: 'Bhubaneswar Airport (60 km).',
      train: 'Puri Railway Station (2 km) is a major East Coast terminus.',
      road: 'Direct 4-lane highway from Bhubaneswar (60 km).',
    },
    verified: true,
    status: 'published',
    isActive: true,
  },
  {
    name: 'Kaziranga National Park',
    slug: 'kaziranga-national-park',
    state: 'assam',
    stateName: 'Assam',
    city: 'guwahati',
    cityName: 'Guwahati',
    category: 'wildlife',
    categoryName: 'Wildlife',
    shortDescription: 'World sanctuary of the great Indian one-horned rhinoceros, sprawling across the fertile floodplains of the Brahmaputra.',
    description: 'A UNESCO World Heritage Site in Assam, Kaziranga hosts two-thirds of the world’s great one-horned rhinoceroses. Spanning elephant grass, dense tropical moist broadleaf forests, and numerous water bodies, it also boasts the highest density of tigers in protected areas and is home to large breeding populations of elephants and wild water buffalo.',
    historicalSignificance: 'Created in 1905 when Mary Curzon, wife of the Viceroy Lord Curzon, persuaded him to take urgent conservation steps after failing to spot a single rhino.',
    culturalSignificance: 'A global triumph of grassroots conservation and anti-poaching vigilance in the biodiversity heart of Assam.',
    bestTimeToVisit: 'November to April (Park closed during monsoon floods May to October)',
    recommendedDuration: '2 days',
    openingHours: 'Jeep safaris: 7:30 AM to 10:00 AM & 1:30 PM to 3:00 PM; Elephant rides at dawn',
    entryFee: 'Park entry ₹100 for Indian nationals, ₹650 for Foreign visitors; Jeep vehicle fees separate',
    location: 'Kanchanjuri, Golaghat and Nagaon districts, Assam 785609',
    mapUrl: 'https://maps.google.com/?q=Kaziranga+National+Park+Assam',
    images: [
      'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Kaziranga National Orchid Park', 'Hollongapar Gibbon Sanctuary', 'Kakochang Waterfalls', 'Tea Garden Walks'],
    travelTips: [
      'Book jeep safaris in Central (Kohora) and Western (Bagori) ranges for best rhino and swamp deer sightings.',
      'Visit the nearby Kaziranga Orchid and Biodiversity Park to see over 500 indigenous wild orchid species.',
    ],
    howToReach: {
      air: 'Jorhat Airport (97 km) or Guwahati International Airport (217 km).',
      train: 'Furkating Railway Station (75 km) or Guwahati (200 km).',
      road: 'Located right on NH 715 with frequent buses and cabs from Guwahati.',
    },
    verified: true,
    status: 'verified',
    isActive: true,
  },
  {
    name: 'Darjeeling Himalayan Railway & Tiger Hill',
    slug: 'darjeeling-himalayan-railway-tiger-hill',
    state: 'west-bengal',
    stateName: 'West Bengal',
    city: 'darjeeling',
    cityName: 'Darjeeling',
    category: 'hill-stations',
    categoryName: 'Hill Stations',
    shortDescription: 'The legendary colonial hill town with the UNESCO "Toy Train" steam railway and golden sunrise vistas over Mount Kanchenjunga.',
    description: 'Perched at 2,042 meters in the Lesser Himalayas of West Bengal, Darjeeling is synonymous with the world’s finest champagne tea. The historic Darjeeling Himalayan Railway (a narrow-gauge mountain railway built in 1881) climbs through zig-zags and the Batasia Loop. At Tiger Hill, dawn reveals the snow-mantled peaks of Kanchenjunga bathed in crimson gold.',
    historicalSignificance: 'Developed as a sanatorium and summer headquarters by the British East India Company in the mid-19th century.',
    culturalSignificance: 'A vibrant mosaic of Gorkha, Tibetan, Lepcha, and Bengali cultures with Buddhist monasteries and mountaineering academies.',
    bestTimeToVisit: 'October to December and March to May',
    recommendedDuration: '3 to 4 days',
    openingHours: 'Tiger Hill sunrise: 4:00 AM; Toy Train rides scheduled throughout the day',
    entryFee: 'Tiger Hill observatory: ₹50; Toy Train joyride: ₹1000-₹1500 (Steam/Diesel)',
    location: 'Darjeeling, West Bengal 734101',
    mapUrl: 'https://maps.google.com/?q=Darjeeling+West+Bengal',
    images: [
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Batasia Loop', 'Himalayan Mountaineering Institute', 'Happy Valley Tea Estate', 'Ghum Monastery'],
    travelTips: [
      'Start for Tiger Hill at 3:30 AM to secure a front parking spot and clear viewing platform angle.',
      'Book the Darjeeling to Ghum steam joyride in advance on IRCTC as tickets sell out rapidly.',
    ],
    howToReach: {
      air: 'Bagdogra Airport (70 km).',
      train: 'New Jalpaiguri (NJP) Railway Station (75 km).',
      road: 'Scenic 3-hour hill drive from Siliguri via Rohini or Hill Cart Road.',
    },
    verified: true,
    status: 'published',
    isActive: true,
  },
  {
    name: 'Victoria Memorial',
    slug: 'victoria-memorial',
    state: 'west-bengal',
    stateName: 'West Bengal',
    city: 'kolkata',
    cityName: 'Kolkata',
    category: 'heritage',
    categoryName: 'Heritage',
    shortDescription: 'A colossal white Makrana marble monument in Kolkata, blending Indo-Saracenic revivalist and British classical architecture.',
    description: 'Commissioned in 1906 by Lord Curzon to commemorate Queen Victoria, the Victoria Memorial stands amidst 64 acres of landscaped gardens on the Maidan. Built from the same white Makrana marble as the Taj Mahal, it houses 25 galleries containing royal portraits, colonial sculptures, historical documents, and rare Bengal school paintings.',
    historicalSignificance: 'Represents the grandeur and imperial ambitions of British India when Kolkata was the capital of the British Raj.',
    culturalSignificance: 'A beloved cultural landmark and gathering ground for generations of Kolkata citizens and scholars of the Bengal Renaissance.',
    bestTimeToVisit: 'October to March (Pleasant winter climate)',
    recommendedDuration: '2 to 3 hours',
    openingHours: 'Gardens: 5:30 AM to 6:15 PM; Museum: 10:00 AM to 5:00 PM (Closed Mondays)',
    entryFee: 'Garden ₹50; Museum Gallery ₹50 for Indian nationals, ₹500 for Foreign tourists',
    location: '1, Queens Way, Maidan, Kolkata, West Bengal 700071',
    mapUrl: 'https://maps.google.com/?q=Victoria+Memorial+Kolkata',
    images: [
      'https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Howrah Bridge', 'St. Paul’s Cathedral', 'Indian Museum Kolkata', 'Dakshineswar Kali Temple'],
    travelTips: [
      'Attend the evening sound and light show narrating the story of Calcutta’s founding and evolution.',
      'Take an iconic yellow taxi ride or horse-drawn carriage around the Victoria Memorial periphery.',
    ],
    howToReach: {
      air: 'Netaji Subhash Chandra Bose International Airport (18 km).',
      train: 'Howrah Junction (5 km) or Sealdah Railway Station (4 km).',
      road: 'Easily accessible via Kolkata Metro (Rabindra Sadan or Maidan stations).',
    },
    verified: true,
    status: 'published',
    isActive: true,
  },
  {
    name: 'Sundarbans Mangrove Reserve',
    slug: 'sundarbans-mangrove-reserve',
    state: 'west-bengal',
    stateName: 'West Bengal',
    city: 'kolkata',
    cityName: 'Kolkata',
    category: 'wildlife',
    categoryName: 'Wildlife',
    shortDescription: 'The world’s largest coastal mangrove forest on the delta of the Ganga and Brahmaputra, habitat of the swimming Royal Bengal Tiger.',
    description: 'The Sundarbans delta is an interconnected web of tidal waterways, mudflats, and halophytic mangrove islands. It is a UNESCO Biosphere Reserve and the only mangrove forest in the world inhabited by tigers that have adapted to swimming in tidal currents. The reserve is also home to estuarine crocodiles, spotted deer, and endangered Irrawaddy dolphins.',
    historicalSignificance: 'Protected since the early British forestry acts of 1878, preserving ancient coastal ecology against storm surges.',
    culturalSignificance: 'Rich local folklore of Bonbibi, the forest guardian deity worshiped equally by Hindu and Muslim honey collectors and fishermen.',
    bestTimeToVisit: 'November to February (Cool weather and optimal wildlife visibility along river banks)',
    recommendedDuration: '2 to 3 days',
    openingHours: 'Boat safaris operate from 7:00 AM to 5:00 PM with licensed guides',
    entryFee: 'Boat permit and forest entry ₹60 per head for Indian nationals, ₹200 for Foreign visitors',
    location: 'Sundarbans, South 24 Parganas, West Bengal 743370',
    mapUrl: 'https://maps.google.com/?q=Sundarbans+National+Park',
    images: [
      'https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Sajnekhali Watch Tower', 'Dobanki Canopy Walk', 'Sudhanyakhali Watch Tower', 'Netidhopani Ruins'],
    travelTips: [
      'Dress in earthy colors (khaki, olive green) and maintain absolute silence on safari boats.',
      'Carry binocular optics and warm layers for chilly morning boat cruises along wide estuaries.',
    ],
    howToReach: {
      air: 'Kolkata Airport (110 km).',
      train: 'Canning Railway Station (45 km from boat embarkation at Godkhali jetty).',
      road: '3-hour drive from Kolkata to Godkhali Ferry Ghat, followed by boat travel.',
    },
    verified: true,
    status: 'published',
    isActive: true,
  },
  {
    name: 'Golden Temple (Sri Harmandir Sahib)',
    slug: 'golden-temple-sri-harmandir-sahib',
    state: 'punjab',
    stateName: 'Punjab',
    city: 'amritsar',
    cityName: 'Amritsar',
    category: 'religious',
    categoryName: 'Religious',
    shortDescription: 'The spiritual heart of Sikhism, bathed in real gold foil atop the holy Amrit Sarovar, home to the world’s largest free communal kitchen.',
    description: 'Sri Harmandir Sahib, known worldwide as the Golden Temple, was designed by Guru Arjan Dev Ji with four entrances symbolizing openness to all castes, creeds, and faiths. The upper floors of the gurdwara were gilded with 500 kg of pure gold leaf by Maharaja Ranjit Singh in 1830. The community kitchen (Guru ka Langar) serves over 100,000 free hot vegetarian meals every single day.',
    historicalSignificance: 'Founded by Guru Ram Das Ji in 1577; the foundation stone of the sanctum sanctorum was laid by the venerated Sufi saint Hazrat Mian Mir of Lahore in 1589.',
    culturalSignificance: 'The ultimate embodiment of egalitarian humility, selfless service (Seva), and devotional Gurbani kirtan echoing day and night.',
    bestTimeToVisit: 'October to March',
    recommendedDuration: '3 to 5 hours',
    openingHours: 'Open 24 hours every day',
    entryFee: 'Free entry for all human beings',
    location: 'Golden Temple Rd, Atta Mandi, Amritsar, Punjab 143006',
    mapUrl: 'https://maps.google.com/?q=Golden+Temple+Amritsar',
    images: [
      'https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Jallianwala Bagh', 'Attari-Wagah Border Flag Lowering', 'Partition Museum', 'Gobindgarh Fort'],
    travelTips: [
      'Cover your head with a scarf or bandana and wash your feet at the running water channel before entry.',
      'Volunteer for a few minutes in the Langar hall rolling rotis or washing plates for a deeply humbling spiritual experience.',
    ],
    howToReach: {
      air: 'Sri Guru Ram Dass Jee International Airport Amritsar (13 km).',
      train: 'Amritsar Junction Railway Station (2 km).',
      road: 'Directly linked via Grand Trunk Road (NH 44) from New Delhi (450 km).',
    },
    verified: true,
    status: 'verified',
    isActive: true,
  },
  {
    name: 'Khajuraho Group of Monuments',
    slug: 'khajuraho-monuments',
    state: 'madhya-pradesh',
    stateName: 'Madhya Pradesh',
    city: 'khajuraho',
    cityName: 'Khajuraho',
    category: 'temples',
    categoryName: 'Temples',
    shortDescription: 'Celebrated UNESCO medieval temples famous for Nagara-style sandstone spires and exquisite sensuous sculptural art.',
    description: 'Built between 950 and 1050 CE by the Chandela dynasty, the Khajuraho temples in central India represent a triumph of sculptural expressiveness. Of the original 85 temples, 25 survive in three complexes. The Western Group, including the monumental Kandariya Mahadeva Temple, features soaring fractal shikhara spires and intricate carvings depicting gods, celestial nymphs, and human intimacy.',
    historicalSignificance: 'Protected by surrounding dense teak forests after the decline of the Chandelas until British surveyor T.S. Burt uncovered them in 1838.',
    culturalSignificance: 'A profound celebration of the four goals of Hindu life: Dharma, Artha, Kama, and Moksha through high classical sculpture.',
    bestTimeToVisit: 'October to March (Khajuraho Dance Festival takes place in February)',
    recommendedDuration: '1 to 2 days',
    openingHours: 'Sunrise to Sunset',
    entryFee: '₹40 for Indian nationals, ₹600 for Foreign visitors (Western Group)',
    location: 'Rajnagar, Khajuraho, Chhatarpur District, Madhya Pradesh 471606',
    mapUrl: 'https://maps.google.com/?q=Khajuraho+Temples+Madhya+Pradesh',
    images: [
      'https://images.unsplash.com/photo-1620619767323-b95a89183081?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Kandariya Mahadeva Temple', 'Panna National Park (Tiger Reserve)', 'Raneh Waterfalls Canyon', 'Ajaigarh Fort'],
    travelTips: [
      'Attend the evening sound and light show narrated by Amitabh Bachchan in both Hindi and English.',
      'Take a day trip to Raneh Falls (20 km away) to see the dramatic multi-colored crystalline granite canyon.',
    ],
    howToReach: {
      air: 'Khajuraho Airport (5 km) with direct flights from Delhi and Varanasi.',
      train: 'Khajuraho Railway Station (8 km).',
      road: 'Linked to Jhansi (175 km) and Satna (120 km) via state highways.',
    },
    verified: true,
    status: 'verified',
    isActive: true,
  },
  {
    name: 'Palolem Beach & Old Goa Heritage',
    slug: 'palolem-beach-goa',
    state: 'goa',
    stateName: 'Goa',
    city: 'panaji',
    cityName: 'Panaji',
    category: 'beaches',
    categoryName: 'Beaches',
    shortDescription: 'A crescent-shaped golden sand paradise in South Goa framed by rocky headlands, swaying palms, and calm turquoise waters.',
    description: 'Palolem Beach in Canacona is one of Goa’s most picturesque shores, known for its gentle shelving seabed making it safe for swimming. In contrast to north Goa’s party strips, Palolem retains a laid-back charm with colorful beach shacks, kayak excursions to Butterfly Beach, dolphin-watching boat trips, and silent headphone parties.',
    historicalSignificance: 'South Goa preserves early pre-colonial Konkani fishing settlements alongside Portuguese manor houses and chapel shrines.',
    culturalSignificance: 'The quintessence of Goa’s "Susegad" lifestyle—a relaxed, contented state of mind immersed in sea breeze and coastal hospitality.',
    bestTimeToVisit: 'November to March',
    recommendedDuration: '2 to 3 days',
    openingHours: 'Open 24 hours (Water activities available from 8:00 AM to 6:00 PM)',
    entryFee: 'Free public beach access',
    location: 'Canacona, South Goa, Goa 403702',
    mapUrl: 'https://maps.google.com/?q=Palolem+Beach+Goa',
    images: [
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Agonda Beach', 'Cabo de Rama Fort', 'Butterfly Island', 'Basilica of Bom Jesus (Old Goa)'],
    travelTips: [
      'Rent a sea kayak in the early morning to explore the sheltered northern lagoon and Monkey Island.',
      'Savor authentic Goan fish thali and coconut curry at traditional village taverns just off the beach lane.',
    ],
    howToReach: {
      air: 'Dabolim Airport (60 km) or Manohar International Airport Mopa (105 km).',
      train: 'Canacona Railway Station (3 km) or Madgaon Junction (35 km).',
      road: 'Scenic drive down NH 66 through coconut groves and river bridges.',
    },
    verified: true,
    status: 'published',
    isActive: true,
  },
  {
    name: 'Red Fort & Qutub Minar',
    slug: 'qutub-minar-red-fort-delhi',
    state: 'delhi',
    stateName: 'Delhi',
    city: 'new-delhi',
    cityName: 'New Delhi',
    category: 'heritage',
    categoryName: 'Heritage',
    shortDescription: 'Towering symbols of Delhi’s imperial millennia: the 73-meter fluted minaret of Qutub and the red sandstone citadel of the Mughals.',
    description: 'Delhi’s rich tapestry is anchored by UNESCO World Heritage sites: Qutub Minar, the world’s tallest brick minaret started in 1192 by Qutb-ud-din Aibak surrounded by the ancient rust-resistant Iron Pillar; and the massive Red Fort (Lal Qila) built by Shah Jahan in 1648, featuring the Lahori Gate and Diwan-i-Aam.',
    historicalSignificance: 'Epicenter of political power under the Delhi Sultanate, the Mughal Empire, and modern India where the Prime Minister unfurls the national tricolor on Independence Day.',
    culturalSignificance: 'A living testament to Delhi’s seven historic cities, blending Afghan, Persian, and Hindu architectural languages.',
    bestTimeToVisit: 'October to March',
    recommendedDuration: 'Half day each',
    openingHours: '7:00 AM to 6:00 PM daily (Red Fort closed on Mondays)',
    entryFee: '₹50 for Indian nationals, ₹550 for Foreign visitors',
    location: 'Mehrauli & Netaji Subhash Marg, New Delhi 110030',
    mapUrl: 'https://maps.google.com/?q=Qutub+Minar+New+Delhi',
    images: [
      'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',
    ],
    nearbyAttractions: ['Humayun’s Tomb', 'India Gate', 'Lotus Temple', 'Chandni Chowk'],
    travelTips: [
      'Use the Delhi Metro (Yellow line) to travel seamlessly between Qutub Minar station and Chandni Chowk / Red Fort.',
      'Examine the 4th-century Gupta Iron Pillar at Qutub complex, famous for zero corrosion after 1,600 years.',
    ],
    howToReach: {
      air: 'Indira Gandhi International Airport (14 km).',
      train: 'New Delhi Railway Station (12 km) or Hazrat Nizamuddin (8 km).',
      road: 'Extensively covered by Delhi Metro network and electric city buses.',
    },
    verified: true,
    status: 'verified',
    isActive: true,
  },
  {
    name: 'Dal Lake & Mughal Gardens',
    slug: 'dal-lake-srinagar',
    state: 'jammu-and-kashmir',
    stateName: 'Jammu and Kashmir',
    city: 'srinagar',
    cityName: 'Srinagar',
    category: 'lakes',
    categoryName: 'Lakes',
    shortDescription: 'The "Jewel in the crown of Kashmir", featuring carved wooden cedar houseboats, floating vegetable markets, and Nishat Bagh.',
    description: 'Covering 18 square kilometers in the heart of Srinagar, Dal Lake is renowned for its tranquil mirrors of water framed by the snow-capped peaks of the Zabarwan range. Visitors glide on colorful cushioned Shikara boats past floating lotus gardens (Radh) and visit the tiered cascading terraces of Shalimar Bagh and Nishat Bagh laid out by Emperor Jahangir.',
    historicalSignificance: 'Mughal emperors declared Kashmir an earthly paradise ("Agar firdous bar roo-e zameen ast..."), creating geometric Persian pleasure gardens around the lake.',
    culturalSignificance: 'A distinct aquatic lifestyle where Kashmiri bakeries, post offices, flower vendors, and artisans operate directly from wooden skiffs.',
    bestTimeToVisit: 'April to October (Spring tulip bloom to golden Chinar autumn)',
    recommendedDuration: '2 to 3 days',
    openingHours: 'Shikaras operate from 5:30 AM to 9:00 PM; Gardens open 9:00 AM to 7:00 PM',
    entryFee: 'Mughal Gardens ₹24; Shikara rides ₹500 to ₹1200 per hour',
    location: 'Boulevard Road, Srinagar, Jammu and Kashmir 190001',
    mapUrl: 'https://maps.google.com/?q=Dal+Lake+Srinagar',
    images: [
      'https://images.pexels.com/photos/36856158/pexels-photo-36856158.jpeg?_gl=1*19bips*_ga*MjA5MjM0ODU4OS4xNzkwNTY0OTkw*_ga_8JE65Q40S6*czE3OTA1NjQ5OTAkbzEkZzEkdDE3OTA1NjYxNDQkajEwJGwwJGgw',
      'https://images.pexels.com/photos/25786716/pexels-photo-25786716.jpeg?_gl=1*qhikqv*_ga*MjA5MjM0ODU4OS4xNzkwNTY0OTkw*_ga_8JE65Q40S6*czE3OTA1NjQ5OTAkbzEkZzEkdDE3OTA1NjU3OTkkajYwJGwwJGgw',
    ],
    nearbyAttractions: ['Nishat Bagh', 'Shalimar Bagh', 'Shankaracharya Temple', 'Hazratbal Shrine', 'Gulmarg'],
    travelTips: [
      'Wake up before dawn for a 5:30 AM shikara ride to experience the bustling floating vegetable market.',
      'Sip a warm cup of authentic Kashmiri Kahwa brewed with saffron, crushed almonds, and cardamom while cruising.',
    ],
    howToReach: {
      air: 'Sheikh ul-Alam International Airport Srinagar (14 km).',
      train: 'Udhampur/Jammu Tawi Railway Station with direct train connectivity extending through Banihal.',
      road: 'NH 44 connects Jammu to Srinagar through the landmark Chenani-Nashri and Banihal Qazigund tunnels.',
    },
    verified: true,
    status: 'verified',
    isActive: true,
  },
];

export const initialAdmin = {
  name: 'Chief Curator',
  email: 'admin@travelbharat.gov.in',
  password: 'AdminPassword123!',
  role: 'superadmin',
};

export const hashPassword = async (pwd) => {
  const salt = await bcrypt.genSalt(10);
  return bcrypt.hash(pwd, salt);
};
